matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      code_languages:  # specify languages to ignore in code blocks
        - python
        - plantuml
        - zsh
      ignore_patterns:  # custom pattern to ignore References section
        - '## References\n(?:- .*\n)*'
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
