matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
      - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      ignore_patterns:  # custom patterns to ignore References section and code blocks
        - '```[a-zA-Z]+\n[\s\S]*?\n```'  # ignore code blocks wrapped in triple backticks
        - '## References\n(?:- .*\n)*'  # ignore the "References" section
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
    - '**/*.md'
  default_encoding: utf-8
