site_name: Research Software Engineering Team Blog
site_description: The Research Software Engineering Team Blog
site_url: https://imperialcollegelondon.github.io/RSEBlog/
repo_url: https://github.com/ImperialCollegeLondon/RSEBlog

theme:
  name: material
  logo: assets/imperial_bw.svg
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog:
      blog_dir: .
      categories: true
      categories_allowed:
        - Events
        - Technology
      categories_toc: true
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
