site_name: Research Software Engineering Team Blog
site_description: The Research Software Engineering Team Blog
site_url: https://imperialcollegelondon.github.io/RSEBlog/
repo_url: https://github.com/ImperialCollegeLondon/RSEBlog

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/imperial_bw.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - https://cdn.usefathom.com/script.js

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog:
      blog_dir: .
      categories: true
      categories_allowed:
        - Events
        - Technology
      categories_toc: true
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - caption:
      figure:
        ignore_classes: ['no-caption']

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: True
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
