authors:
  AdrianDAlessandro:
    name: Adrian D'Alessandro
    description: Senior Research Software Engineer
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/AdrianDAlensandro.png
  alexdewar:
    name: Alexander Dewar
    description: Senior Research Software Engineer
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/Dewar.jpg
  HarmonicReflux:
    name: Benjamin J Scharpf
    description: HPC and RSE Experience Programme
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/Benjamin_Scharpf.png
  cc-a:
    name: Chris Cave-Ayland
    description: RSE Technical Lead
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/Chris_bw.png
  dc2917:
    name: Daniel Cummins
    description: Research Software Engineer
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/dc_cropped_greyscale.jpg
  dalonsoa:
    name: Diego Alonso Álvarez
    description: Head of RSEs
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/Diego_bw.png
  jamesturner246:
    name: James Turner
    description: Senior Research Software Engineer
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/JamesTurner.png
  TinyMarsh:
    name: Ryan Smith
    description: Senior Research Software Engineer
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/Smith.jpg
  Sahil590:
    name: Sahil Raja
    description: Junior Software Developer
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/Sahil_bw.png
  SaranjeetKaur:
    name: Saranjeet Kaur Bhogal
    description: Research Software Engineer
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/Saranjet_Kaur_Bhogal.png
  tsmbland:
    name: Tom Bland
    description: Research Software Engineer
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list/TomBland.png
  dandavies:
    name: Dan Davies
    description: Senior Research Software Engineer (former member)
    avatar: https://github.com/dandavies99.png
