authors:
  dalonsoa:
    name: Diego Alonso Álvarez
    description: Head of RSEs
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list-300X400/Diego_bw.png
  cc-a:
    name: Chris Cave-Ayland
    description: RSE Technical Lead
    avatar: https://pxl-imperialacuk.terminalfour.net/fit-in/428x572/filters:upscale()/prod01/channel_2/media/images/people-list-300X400/Chris_bw.png
