name: CI checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Check that documentation builds cleanly with MkDocs
        run: mkdocs build --strict
