name: CI checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.8.3
      - name: Install dependencies
        run: poetry install
      - name: Check that documentation builds cleanly with MkDocs
        run: poetry run mkdocs build --strict
